version: '3'
services:
  powerstat:
    build: .
    container_name: powerstat-container
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/cpu:/dev/cpu
    stdin_open: true
    tty: true
    volumes:
      - ./powerstat_output:/output
    command: bash -c "sudo /usr/local/bin/power.sh 5 0.5"
